"""GitHub integration: push solutions, create PRs, manage repos."""
import json
from datetime import datetime
from typing import Optional

from github import Github, GithubException

from .config import settings


def get_github_client() -> Optional[Github]:
    if not settings.github_token:
        return None
    return Github(settings.github_token)


def push_solution_to_github(lab_slug: str, steps: list[dict], summary: str) -> dict:
    """Push solution files to the configured GitHub repo."""
    gh = get_github_client()
    if not gh or not settings.github_repo:
        return {"success": False, "message": "GitHub not configured"}

    try:
        repo = gh.get_repo(settings.github_repo)
        branch = f"solution/{lab_slug}-{datetime.utcnow().strftime('%Y%m%d-%H%M%S')}"

        # Get default branch SHA
        default_branch = repo.default_branch
        ref = repo.get_git_ref(f"heads/{default_branch}")
        base_sha = ref.object.sha

        # Create new branch
        repo.create_git_ref(ref=f"refs/heads/{branch}", sha=base_sha)

        # Build solution files
        files = _build_solution_files(lab_slug, steps, summary)

        for file_path, content in files.items():
            try:
                existing = repo.get_contents(file_path, ref=branch)
                repo.update_file(file_path, f"Update solution: {lab_slug}", content, existing.sha, branch=branch)
            except GithubException:
                repo.create_file(file_path, f"Add solution: {lab_slug}", content, branch=branch)

        # Create PR
        pr = repo.create_pull(
            title=f"Solution: {lab_slug}",
            body=f"## Auto-generated solution\n\n{summary}\n\nGenerated by HoDIDit",
            head=branch,
            base=default_branch,
        )

        return {"success": True, "pr_url": pr.html_url, "branch": branch}
    except Exception as e:
        return {"success": False, "message": str(e)}


def _build_solution_files(lab_slug: str, steps: list[dict], summary: str) -> dict[str, str]:
    files = {}

    # README for this solution
    readme_lines = [f"# Solution: {lab_slug}\n", f"{summary}\n\n## Steps\n"]
    for i, step in enumerate(steps, 1):
        readme_lines.append(f"### {i}. {step['title']} `[{step['type']}]`\n")
        if step["type"] in ("command", "git"):
            readme_lines.append(f"```bash\n{step['content']}\n```\n")
        elif step["type"] == "code":
            readme_lines.append(f"```python\n{step['content']}\n```\n")
        else:
            readme_lines.append(f"{step['content']}\n")
        if step.get("output"):
            readme_lines.append(f"**Output:**\n```\n{step['output']}\n```\n")

    files[f"solutions/{lab_slug}/README.md"] = "".join(readme_lines)
    files[f"solutions/{lab_slug}/solution.json"] = json.dumps(
        {"lab_slug": lab_slug, "summary": summary, "steps": steps}, indent=2
    )

    # Extract runnable scripts
    commands = [s["content"] for s in steps if s["type"] in ("command", "git")]
    if commands:
        files[f"solutions/{lab_slug}/run.sh"] = "#!/bin/bash\nset -e\n\n" + "\n".join(commands)

    python_steps = [s for s in steps if s["type"] == "code"]
    for i, step in enumerate(python_steps, 1):
        files[f"solutions/{lab_slug}/solution_{i}.py"] = step["content"]

    return files
